config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#index'

  resources :users, only: [:index, :show] do
    member do
      get :likes, :followings, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :new, :create, :destroy] do
    collection do
      get :trend, :all
    end
    resources :comments, only: [:create, :destroy]
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/views/shared/_footer.html.haml
.footer
  &copy; 2021 Revorite 
  = link_to 'https://twitter.com/345dvl', target: "_blank", title: "Twitter" do
    %i.fab.fa-twitter
  = link_to 'https://github.com/345dvl/revorite', target: "_blank", title: "Githubリポジトリ" do
    %i.fab.fa-github

app/views/shared/_header.html.haml
.hidden
  %p#star-none{image_path: asset_path('star/none.png')}
  %p#star-full{image_path: asset_path('star/full.png')}
  %p#star-half{image_path: asset_path('star/half.png')}
.header
  .header-left
    .header-left-title
      = link_to root_path, "data-turbolinks": false do
        Revorite
    .header-left-pagename
      - case request.fullpath
      - when /\/users\/[0-9]+/ 
        - if user_signed_in?
          - if @user.id == current_user.id
            ｜ マイページ
          - else
            ｜ ユーザ情報
        - else
          ｜ ユーザ情報
      - when "/users/sign_up"
        ｜ 新規登録
      - when "/users/sign_in"
        ｜ ログイン
      - when "/users/edit"
        ｜ プロフィールの変更
      - when "/users"
        ｜ プロフィールの変更
      - when /\/users\/password.*/
        ｜ パスワードの再発行
      - when "/posts/new"
        ｜ 新規投稿
        
  .header-right
    .header-right-newpost
      - if user_signed_in?
        - if request.fullpath != "/posts/new"
          = link_to new_post_url, "data-turbolinks": false do
            .button-newpost
              %i.fas.fa-feather-alt
              投稿する
    .header-right-menu
      %ul
        - if user_signed_in?
          = link_to user_path(current_user.id), "data-turbolinks": false do
            %li
              - if current_user.image.attached? 
                = image_tag(current_user.image, alt: 'デフォルトアイコン')
              - else
                = image_tag('sample/default_icon.png', alt: 'デフォルトアイコン')
            %li#username
              = current_user.name
          %li
            = link_to destroy_user_session_path, method: :delete do
              %i.fas.fa-sign-out-alt
              ログアウト
        - else
          %li.easylogin
            = link_to users_guest_sign_in_path, method: :post, "data-turbolinks": false do
              %i.fas.fa-user-check
              かんたんログイン
            %i.fas.fa-question-circle
              .fukidashi
                ゲストユーザとしてワンクリックでログインができます
          - if current_page?(new_user_session_path)
            %li{style: "font-weight: bold;"}
              %i.fas.fa-sign-in-alt
              ログイン 
          - else
            %li
              = link_to new_user_session_path, "data-turbolinks": false do
                %i.fas.fa-sign-in-alt
                ログイン
          - if current_page?(new_user_registration_path)
            %li{style: "font-weight: bold;"}
              %i.fas.fa-plus
              新規登録 
          - else
            %li
              = link_to new_user_registration_path, "data-turbolinks": false do
                %i.fas.fa-plus
                新規登録

app/views/shared/_top-header.html.haml
.header
  .header-left
    .header-left-title
      = link_to root_path, "data-turbolinks": false do
        Revorite
    .header-left-pagename
      - case request.fullpath
      - when /users\// 
        - if user_signed_in?
          - if @user.id == current_user.id
            ｜ マイページ
          - else
            ｜ ユーザ情報
        - else
          ｜ ユーザ情報
      - when "/posts/new"
        ｜ 新規投稿
        
  .header-right
    %ul
      - if user_signed_in?
        = link_to user_path(current_user.id), "data-turbolinks": false do
          %li
            - if current_user.image.attached? 
              = image_tag(current_user.image, alt: 'デフォルトアイコン')
            - else
              = image_tag('sample/default_icon.png', alt: 'デフォルトアイコン')
          %li#username
            = current_user.name
        %li
          = link_to destroy_user_session_path, method: :delete do
            %i.fas.fa-sign-out-alt
            ログアウト
      - else
        %li
          = link_to('#') do
            %i.fas.fa-user-check
            かんたんログイン
        %li
          = link_to new_user_session_path do
            %i.fas.fa-sign-in-alt
            ログイン
        %li
          = link_to new_user_registration_path do
            %i.fas.fa-plus
            新規登録