config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#index'

  resources :users, only: [:index, :show] do
    member do
      get :likes, :followings, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :new, :create, :destroy] do
    collection do
      get :trend, :all
    end
    resources :comments, only: [:create, :destroy]
    resources :reposts, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true, unless: Proc.new {images.attached?}
  validates :text, length: { maximum: 500 }
  include ImagesValidation

  belongs_to :user
  has_many_attached :images
  has_one :review, dependent: :destroy
  accepts_nested_attributes_for :review
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reposts, dependent: :destroy

  attr_accessor :rev_flg

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :all]
  before_action :set_user, only: [:index, :trend, :all]

  def index
    if user_signed_in?
      @posts = @user.followings_posts_with_reposts.page(params[:page]).without_count.per(PAGENATION_PAGES)
    else
      @posts = Post.with_attached_images.preload(:user, :review, :comments, :likes).order(created_at: "DESC").page(params[:page]).without_count.per(PAGENATION_PAGES)
    end
  end

  def trend
    counts = Post.joins(:likes).group(:id).order(count_all: "DESC").order(created_at: "DESC").count
    @posts = Post.with_attached_images.preload(:user, :review, :comments, :likes).find(counts.map{|id, count| id})
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(PAGENATION_PAGES)
  end

  def all
    @posts = Post.with_attached_images.preload(:user, :review, :comments, :likes).order(created_at: "DESC").page(params[:page]).without_count.per(PAGENATION_PAGES)
  end

  def new
    @post = Post.new
  end

  def create
    if params[:post][:rev_flg] == '0'  # 「レビューをする」にチェックが無い場合
      @post = Post.new(post_params)
    else
      @post = Post.new(post_params_with_review)
    end  
    if @post.save
      redirect_to :root, notice: "投稿に成功しました"
    else
      render :new
    end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    if post.present?
      if post.destroy
        redirect_back fallback_location: root_path, notice: "投稿を削除しました"
      else
        redirect_back fallback_location: root_path, alert: "投稿の削除に失敗しました"
      end
    else
      redirect_back fallback_location: root_path, alert: "投稿が見つかりません"
    end
  end

  private
  def post_params
    params.require(:post).permit(:rev_flg, :text, images: []).merge(user_id: current_user.id)
  end

  def post_params_with_review
    params.require(:post).permit(:rev_flg, :text, images: [], review_attributes: [:rate, :title, :price]).merge(user_id: current_user.id)
  end

  def set_user
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.haml
.post-header
  .post-header__name
    = link_to user_path(post.user.id), "data-turbolinks": false do
      = post.user.name
  .post-header__time
    %i.far.fa-clock
    = post.created_at.to_s(:human)
  - if user_signed_in?
    - if post.user_id == current_user.id
      .post-header__delete
        = link_to("/posts/#{post.id}", method: :delete, title: "投稿を削除する", data: {confirm: "投稿を削除してよろしいですか？"}) do
          %i.fas.fa-trash-alt
- if post.review.present?
  .post-review
    .post-review-star{id: "star-#{post.id}", rate: "#{post.review.rate}"}
    .post-review-title
      = post.review.title
    .post-review-price
      - if post.review.price.present?
        = "¥" + post.review.price.to_s(:delimited)
    .post-review-google.review-img
      = link_to "http://www.google.co.jp/search?q=#{CGI.escape(post.review.title)}", target: "_blank" do
        = image_tag asset_path("google.png"), title: "Googleで検索する", size: "20x20"
    .post-review-amazon.review-img
      = link_to "https://www.amazon.co.jp/s?k=#{CGI.escape(post.review.title)}", target: "_blank" do
        = image_tag asset_path("amazon.png"), title: "Amazonで検索する", size: "20x20"
    .post-review-rakuten.review-img
      = link_to "https://search.rakuten.co.jp/search/mall/#{CGI.escape(post.review.title)}", target: "_blank" do
        = image_tag asset_path("rakuten.png"), title: "楽天で検索する", size: "20x20"
    .post-review-kakakudotcom.review-img
      = link_to "https://kakaku.com/search_results/#{CGI.escape(post.review.title.encode("cp932"))}/?act=Input", target: "_blank" do
        = image_tag asset_path("kakakudotcom.png"), title: "価格.comで検索する", size: "20x20"
.post-text
  = raw Rinku.auto_link(h(simple_format(post.text)), :urls, 'target="_blank"')
- if post.images.attached?
  .post-image
    - post.images.each do |image|
      = link_to(url_for(image), class: "luminous-post-#{post.id}") do
        = lazy_image_tag(url_for(image))
.post-action
  .post-action__comment{id: "post-action__comment-#{post.id}", title: "コメントをする・見る" } 
    %p
      %i.far.fa-comment-dots
      = post.comments.length
  .post-action__repost#repost{ id: post.id}
    = render partial: "reposts/repost", locals: {post: post}
  .post-action__fav#like{ id: post.id }
    = render partial: "likes/like", locals: {post: post}

app/views/posts/_posts.html.haml
- if posts.empty?
  %li.post
    - case request.fullpath
    - when /\/users\/[0-9]+\/likes/ then
      .post-container
        お気に入りはまだありません。
    - else
      .post-container
        まだ投稿はありません。
- else
  - posts.each_with_index.each do |post, i|
    %hr
    %li.post
      - if post.has_attribute?(:repost_user_id)
        - if post.repost_user_id.present?
          .post-repost
            %i.fas.fa-retweet
            = link_to post.repost_user_name, "/users/#{post.repost_user_id}", "data-turbolinks": false
            さんがリポスト
      .post-container
        .post-left
          = link_to user_path(post.user.id), "data-turbolinks": false do
            - if post.user.image.attached? 
              = lazy_image_tag(url_for(post.user.image), alt: 'デフォルトアイコン')
            - else
              = image_tag('sample/default_icon.png', alt: 'デフォルトアイコン')
        .post-right
          = render partial: "posts/post", locals: {post: post}
          = render partial: "comments/comment", locals: {post: post}
    

app/views/posts/_site-description.html.haml
.site-description__header
  %span Revorite =
  %span.brawn &nbsp;R
  %span eview + Fa
  %span.orange v
  %span orite.
%ul.site-description__list
  %li あなたの"スキ"をレビューしよう
  %li e.g. 日用品・美容品・家電・オーディオ・音楽・映画・ドラマ・アニメ・本・漫画・行き付けのお店・あなたの「推し」・コンビニの季節限定スイーツ
  %li 
    まずは
    = link_to("アカウント登録", new_user_registration_path, "data-turbolinks": false)
    から、30秒で完了
= render 'posts/sns-share'

app/views/posts/_sns-share.html.haml
.sns-share
  = link_to 'https://twitter.com/share?url=https://www.revorite.net/&text=Revorite&via=345dvl', target: "_blank", title: "Twitterで共有する" do
    .button-twitter.button-sns
      %i.fab.fa-twitter
  = link_to 'http://line.me/R/msg/text/?https://www.revorite.net/', target: "_blank", title: "LINEで共有する" do
    .button-line.button-sns
      %i.fab.fa-line

app/views/posts/all.html.haml
- content_for :no_turbolink, true
= provide(:title, 'みんなの投稿')

= render "shared/header"

.main
  .main-menu-outer
    .main-menu-inner
      - if user_signed_in?
        .profile
          = render partial: 'users/profile', locals: {user: @user}
      - else
        .site-description
          = render partial: 'posts/site-description'
  .main-posts
    .main-posts-header
      %ul.main-posts-header-list
        = link_to root_path, class: 'non-active post-links', "data-turbolinks": false do
          .main-posts-header-list-box
            - if user_signed_in?
              %li タイムライン
              %i.fas.fa-question-circle
                .fukidashi
                  フォローしているユーザの投稿を見ることができます
            - else
              %li みんなの投稿
        - if user_signed_in?
          = link_to all_posts_path, class: 'active post-links', "data-turbolinks": false do 
            .main-posts-header-list-box
              %li みんなの投稿
        = link_to trend_posts_path, class: 'non-active post-links', "data-turbolinks": false do 
          .main-posts-header-list-box
            %li 人気の投稿
            %i.fas.fa-question-circle
              .fukidashi
                お気に入りに多く登録されている投稿を見ることができます
    - if @posts.empty?
      %ul.main-posts-contents.jscroll
        %li.post
          .post-container
            投稿はまだありません。
    - else
      %ul.main-posts-contents.jscroll
        = render partial: "posts/posts", locals: {posts: @posts}
        .main-posts-pagenation
          = link_to_prev_page @posts, '前のページ', class: "prev-page", "data-turbolinks": false
          = link_to_next_page @posts, '次のページ', class: "next-page", "data-turbolinks": false
        
= render "shared/footer"

app/views/posts/index.html.haml
- content_for :no_turbolink, true

= render "shared/header"

.main
  .main-menu-outer
    .main-menu-inner
      - if user_signed_in?
        .profile
          = render partial: 'users/profile', locals: {user: @user}
      - else
        .site-description
          = render partial: 'posts/site-description'
  .main-posts
    .main-posts-header
      %ul.main-posts-header-list
        = link_to root_path, class: 'active post-links', "data-turbolinks": false do
          .main-posts-header-list-box
            - if user_signed_in?
              %li タイムライン
              %i.fas.fa-question-circle
                .fukidashi
                  フォローしているユーザの投稿を見ることができます
            - else
              %li みんなの投稿
        - if user_signed_in?
          = link_to all_posts_path, class: 'non-active post-links', "data-turbolinks": false do 
            .main-posts-header-list-box
              %li みんなの投稿
        = link_to trend_posts_path, class: 'non-active post-links', "data-turbolinks": false do 
          .main-posts-header-list-box
            %li 人気の投稿
            %i.fas.fa-question-circle
              .fukidashi
                お気に入りに多く登録されている投稿を見ることができます
    - if user_signed_in?
      - if @user.followings.count == 0
        %ul.main-posts-contents.jscroll
          %li.post
            .post-container-none
              まだ誰もフォローしていません。フォローした人たちの投稿がここに表示されます。
              %br
              = link_to "みんなの投稿", all_posts_path, "data-turbolinks": false
              や
              = link_to "人気の投稿", trend_posts_path, "data-turbolinks": false 
              から気になる人をフォローしてみましょう。
      - else
        - if @posts.empty?
          %ul.main-posts-contents.jscroll
            %li.post
              .post-container
                投稿はまだありません。
        - else
          %ul.main-posts-contents.jscroll
            = render partial: "posts/posts", locals: {posts: @posts}
            .main-posts-pagenation
              = link_to_prev_page @posts, '前のページ', class: "prev-page", "data-turbolinks": false
              = link_to_next_page @posts, '次のページ', class: "next-page", "data-turbolinks": false
    - else
      %ul.main-posts-contents.jscroll
        = render partial: "posts/posts", locals: {posts: @posts}
        .main-posts-pagenation
          = link_to_prev_page @posts, '前のページ', class: "prev-page", "data-turbolinks": false
          = link_to_next_page @posts, '次のページ', class: "next-page", "data-turbolinks": false
        
= render "shared/footer"

app/views/posts/new.html.haml
- content_for :no_turbolink, true
= provide(:title, '新規投稿')

= render "shared/header"

.main
  .newpost
    .newpost-header
      新規投稿
    .newpost-items
      = form_with model: @post, local: true do |f|
        - if @post.errors.any?
          .newpost-items__error#error_explanation
            %ul
            - @post.errors.full_messages.each do |message| 
              %li= message
        .newpost-items__checkbox
          = f.check_box :rev_flg, class: "checkbox", id: "newpost-rev_flg"
          = f.label :rev_flg, "レビューをする", class: "checkbox-parts", for: "newpost-rev_flg"
        .newpost-items__review
          = f.fields_for :review, @post.build_review do |r|
            .newpost-items__label
              評価
            .newpost-items__field#star
              = r.hidden_field :rate, id: "newpost-input-rate"
            .newpost-items__label
              レビュー対象
              %span.note （50文字以内）
            .newpost-items__field
              = r.text_field :title, placeholder: "商品名・タイトルなど", class: "post-input-title", id: "newpost-input-title"
              .newpost-items__field--caution.post-caution-title
            .newpost-items__label
              価格
              %span.note （任意）
            .newpost-items__field
              = r.text_field :price, class: "post-input-price", id: "newpost-input-price"
              .newpost-items__field--caution.post-caution-price
        .newpost-items__label
          本文
          %span.note （500文字以内）
          %span.textcount#newpost-input-text__textcount
        .newpost-items__field
          = f.text_area :text, class: "post-input-text", id: "newpost-input-text"
          .newpost-items__field--caution.post-caution-text
        .newpost-items__image
          = f.label :images, for: "newpost-file_field" do
            %i.far.fa-image
            画像の投稿
            = f.file_field :images, class: "file_field", id: "newpost-file_field", accept: "image/jpeg, image/png", multiple: true
          %span.note （JPEGまたはPNG形式、4枚まで　1枚当たり3MB以内）
        .newpost-items__previewimages
        .newpost-items__submit
          = f.submit '投稿', class: "button-submit post-newpost post-button-submit", disabled: true
    .newpost-footer
      = link_to("<< トップに戻る", root_path, "data-turbolinks": false)

= render "shared/footer"

app/views/posts/trend.html.haml
- content_for :no_turbolink, true
= provide(:title, '人気の投稿')

= render "shared/header"

.main
  .main-menu-outer
    .main-menu-inner
      - if user_signed_in?
        .profile
          = render partial: 'users/profile', locals: {user: @user}
      - else
        .site-description
          = render partial: 'posts/site-description'
  .main-posts
    .main-posts-header
      %ul.main-posts-header-list
        = link_to root_path, class: 'non-active post-links', "data-turbolinks": false do
          .main-posts-header-list-box
            - if user_signed_in?
              %li タイムライン
              %i.fas.fa-question-circle
                .fukidashi
                  フォローしているユーザの投稿を見ることができます
            - else
              %li みんなの投稿
        - if user_signed_in?
          = link_to all_posts_path, class: 'non-active post-links', "data-turbolinks": false do 
            .main-posts-header-list-box
              %li みんなの投稿
        = link_to trend_posts_path, class: 'active post-links', "data-turbolinks": false do 
          .main-posts-header-list-box
            %li 人気の投稿
            %i.fas.fa-question-circle
              .fukidashi
                お気に入りに多く登録されている投稿を見ることができます
    - if @posts.empty?
      %ul.main-posts-contents.jscroll
        %li.post
          .post-container
            投稿はまだありません。
    - else
      %ul.main-posts-contents.jscroll
        = render partial: "posts/posts", locals: {posts: @posts}
        .main-posts-pagenation
          = link_to_prev_page @posts, '前のページ', class: "prev-page", "data-turbolinks": false
          = link_to_next_page @posts, '次のページ', class: "next-page", "data-turbolinks": false
        
= render "shared/footer"